version: '3'
services:
  db:
    container_name: appointments-db-container
    image: postgres:alpine
    restart: always
    volumes:
      - $HOME/appointments-db-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=appointmentsdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata

  server:
    container_name: appointments-service
    image: appointments-service-image
    build: .
    expose:
      - 8080
    ports:
      - 8080:8080
    links:
      - db

volumes:
  appointments-db-volume:
    driver: local
